/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PAvatar: typeof import('primevue/avatar')['default']
    PBadge: typeof import('primevue/badge')['default']
    PButton: typeof import('primevue/button')['default']
    PCard: typeof import('primevue/card')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PPanel: typeof import('primevue/panel')['default']
    PSelect: typeof import('primevue/select')['default']
    PSelectButton: typeof import('primevue/selectbutton')['default']
    PSplitButton: typeof import('primevue/splitbutton')['default']
    PTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
